<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
?>
<?php $block->renderFileLessToCss(); ?>
<header id="lucian_header123" class="header-container custom-header">
	<div class="header-content header-top-custom">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="header-info-custom"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-info-custom')->toHtml(); ?></div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="options-group" >
						<div class="itemlink-custom">
							<div class="ico_account"><img src="<?php echo $block->getUrl('pub/media/xpec/') ?>account.png" /></div>
							<?php 
								if(!$isLoggedIn){
									echo '<a class="linkheader" href="'.$block->getUrl('customer/account/').'"><span class="text">Mi Cuenta</span></a>';
								}else{
									echo '<a class="linkheader" href="'.$block->getUrl('customer/account/').'">HOLA '.strtoupper($customerSession->getCustomer()->getFirstname()).'</a>&nbsp;&nbsp;<a class="linkheader" href="'.$block->getUrl('customer/account/logout').'"><span class="text">SALIR</span></a>';
								}
							?>
							<!--<a class="linkheader" href="<?php echo $block->getUrl('customer/account/') ?>"><span class="text">Mi Cuenta</span></a>-->
						</div>
						<div class="setting-group hidden-sm hidden-xs " data-block="setting">
							<div class="dynamic-links"><span><?php /* @escapeNotVerified */ echo __('Setting'); ?></span></div>
							
							<div class="link-lang-current" 
							data-role="dropdownDialog"
							data-mage-init='{"dropdownDialog":{
							"appendTo":"[data-block=setting]",
							"triggerTarget":".dynamic-links",
							"timeout": "2000",
							"closeOnMouseLeave": false,
							"closeOnEscape": true,
							"triggerClass":"active",
							"parentClass":"active",
							"buttons":[]}}'>
							
								<?php echo $this->getChildHtml("header.links"); ?>
								<?php echo $this->getChildHtml("store_language"); ?>
								<?php echo $this->getChildHtml("currency"); ?>
							</div>
						</div>
						<?php echo $this->getChildHtml("minicart");?>
					</div>
				</div>
				
			</div>
		</div>
		
	</div>
	<div class="header-content header-bottom-custom">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-sm-6 col-xs-12 col1-header-botton">
					<div class="mobile-bar-icon"><span><?php /* @escapeNotVerified */ echo __('mobile icon'); ?></span></div>
					<div class="logo-home">
						<?php echo $this->getChildHtml("logo"); ?>
					</div>
					
				</div>			
				<div class="col-right col-md-7 col-sm-6 col-xs-12">
					<?php echo $this->getChildHtml("hozmegamenu_top"); ?>
					<div class="options-group" >
						<div class="setting-group hidden-sm hidden-xs " data-block="setting">
							<div class="dynamic-links"><span><?php /* @escapeNotVerified */ echo __('Setting'); ?></span></div>
							
							<div class="link-lang-current" 
							data-role="dropdownDialog"
							data-mage-init='{"dropdownDialog":{
							"appendTo":"[data-block=setting]",
							"triggerTarget":".dynamic-links",
							"timeout": "2000",
							"closeOnMouseLeave": false,
							"closeOnEscape": true,
							"triggerClass":"active",
							"parentClass":"active",
							"buttons":[]}}'>
							
								<?php echo $this->getChildHtml("header.links"); ?>
								<?php echo $this->getChildHtml("store_language"); ?>
								<?php echo $this->getChildHtml("currency"); ?>
								
								
								
							</div>
						</div>
						<?php echo $this->getChildHtml("minicart");?>
						<?php echo $this->getChildHtml("top.search"); ?>
					</div>
					
				</div>
			</div>
		</div>
		<div class="mobile-bar-content">
			<div class ="mobile-bar-close"><?php /* @escapeNotVerified */ echo __('Close'); ?></div>
			<div class="content-inner">	
				<ul class = "tabs-mobile">
					<li class="item item-menu"><?php /* @escapeNotVerified */ echo __('Menu'); ?></li>
					<li class="item item-account"><?php /* @escapeNotVerified */ echo __('Account'); ?></li>
					<li class="item item-setting"><?php /* @escapeNotVerified */ echo __('Setting'); ?></li>
				</ul>
				<div class="tabs-content-mobile tabs-menu">
					<?php echo $this->getChildHtml("mobilemenu"); ?>
				</div>
				<div class="tabs-content-mobile tabs-account" style="display:none;">
					<?php echo $this->getChildHtml("header.links"); ?>
				</div>
				<div class="tabs-content-mobile tabs-setting" style="display:none;">
					<?php echo $this->getChildHtml("store_language_mobile"); ?>
					<?php echo $this->getChildHtml("currency_mobile"); ?>
				</div>
			</div>
		</div>
	</div>
</header>
<script type="text/javascript">
require(["jquery"], function($){
	$(document).ready(function(){
		<!-- show, hide mobile bar content -->
		$(".mobile-bar-icon").click(function(){
			$(".mobile-bar-content").addClass("open");
		});
		$(".mobile-bar-close").click(function(){
			$(".mobile-bar-content").removeClass("open");
		});
		
		<!-- choose tabs-->
		$(".tabs-mobile .item-menu").addClass("active");
		$(".tabs-mobile .item").click(function(){
			$(".tabs-mobile .item").removeClass("active");
			$(this).addClass("active");
		});
		$(".tabs-mobile .item-menu").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-menu").css("display","block");
		});
		$(".tabs-mobile .item-account").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-account").css("display","block");
		});
		$(".tabs-mobile .item-setting").click(function(){
			$(".tabs-content-mobile").css("display","none");
			$(".tabs-setting").css("display","block");
		});
		
	});
});
</script>

