<?php
    $payResponse = $block->getPaymentDetails();
    $date_accepted = new \DateTime($payResponse['date_accepted']);
    
?>
<?php if ($payResponse ==! 0) :?> 
    <?php $obj=json_decode( $payResponse['detalleOrder']->getContent() ); ?>
    <div class="page-title">
        <h1><?php echo $block->escapeHtml(__('Detalles del Pago.')) ?></h1>
    </div>
    <h2 class="sub-title"><?php echo $payResponse['description'] ?></h2>
    <table class="data-table">
        <tbody>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Respuesta de la Transacción:')); ?></b></td>
                <td><?php echo $payResponse['paymenCodeResult'] ?> </td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Orden de Compra:')); ?></td>
                <td><?php echo $payResponse['buyOrder'] ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Código de Autorización:')); ?></b></td>
                <td><?php echo $payResponse['authorizationCode'] ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Fecha Transacción:')); ?></b></td>
                <td><?php echo $date_accepted->format('d-m-Y') ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Respuesta de la Transacción:')); ?></b></td>
                <td><?php echo $date_accepted->format('H:i:s') ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Tarjeta:')); ?></b></td>
                <td><?php echo '************' . $payResponse['cardNumber'] ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Tipo de Pago:')); ?></b></td>
                <td><?php echo $payResponse['detalle']['tipopago']; ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Tipo de Cuotas:')); ?></b></td>
                <td><?php echo $payResponse['detalle']['tipocuotas']; ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Número de Cuotas:')); ?></b></td>
                <td><?php echo $payResponse['sharesNumber'] ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Monto Compra:')); ?></b></td>
                <td><?php echo '$'.$payResponse['amount']; ?></td>
            </tr>
            <tr>
                <td><b><?php echo $block->escapeHtml(__('Detalle de la Compra:')); ?></b></td>
                <td>
                    <?php 
                    echo '<table>';
                    echo '<tr>
                            <td>SKU</td>
                            <td>'.$block->escapeHtml(__('Nombre del Producto')).'</td>
                        </tr>';
                    if(isset($obj)){
                        if(is_array($obj->items)){
                            foreach($obj->items as $item){
                                if($item->price>0){
                                    echo '<tr>';
                                    echo '<td>'.$item->sku.'&nbsp;&nbsp;&nbsp;</td>';
                                    echo '<td>'.$item->name.'</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                    }
                    echo '</table>';
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif;