<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter newletter-custom">
<div class="container">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
				<div class="row">
					<div class="col-md-5 col-sm-12 col-xs-12">
						<div class="text-newletter">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('text-newsletter-custom')->toHtml(); ?>
						</div>
						<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ //echo __('Sign Up for Our Newsletter:') ?></span></label>
					</div>
					<div class="col-md-7 col-sm-12 col-xs-12">
						<div class="control">
							<input name="email" type="email" id="newsletter"
										placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
										data-validate="{required:true, 'validate-email':true}"/>
							<div class="actions">
								<button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Suscríbete') ?>" type="submit">
									<span><?php /* @escapeNotVerified */ echo __('Suscríbete') ?></span>
								</button>
							</div>
						</div>
					</div>
				</div>
            </div>
            
        </form>
    </div>
</div>
</div>
<div id="mensaje-news" style="display:none;" ></div>
<div style="display:none;"><a href="#mensaje-news" class="fancybox">modal</a></div>
<script>
	require([
		"jquery","fancybox",'mage/cookies'
	], function($,fancybox){
		$('.fancybox').fancybox({
			height		: '25',
			autoSize	: true,
			closeClick	: true,
		});
		console.log(jQuery.parseJSON($.mage.cookies.get('mage-messages')));
		if($.mage.cookies.get('mage-messages').length>2){
			var obj=jQuery.parseJSON($.mage.cookies.get('mage-messages'))[0];
			var newstr = obj.text.replace(/\+/g, " ");
			if(obj.type=="success"){
				$("#mensaje-news").html("<strong>Exito!</strong> "+newstr);
				$("#mensaje-news").css({'width':'205px'});
				$('.fancybox').trigger('click');
				$('#mensaje-news').parents('.fancybox-skin').addClass('sus-custom-fancy-xpec');		
			}else{
				$("#mensaje-news").html("<strong>Error!</strong> "+newstr);
				$('.fancybox').trigger('click');
				$('#mensaje-news').parents('.fancybox-skin').addClass('fail-custom-fancy-xpec');		
			}
			$.mage.cookies.clear();
		}
	});
</script>