<footer class="footer-container">
	
	<div class="footer-top">
		<div class="container">
			<?php echo $this->getChildHtml('footer_static')?>
			
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="derechos">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('derechos_reservados')->toHtml();?>
				</div>
				<!-- <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<?php echo $this->getChildHtml('footer.copyright')?>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<?php echo $this->getChildHtml('footer_payment')?>
				</div> -->
			</div>
			<div id="back_top">
				<a href="#back-top"><span><?php /* @escapeNotVerified */ echo __('top'); ?></span></a>
			</div>
		</div>
	</div>
</footer>
<script type="text/javascript">
			
	require(["jquery"], function($){

	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});
		   $('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		});
		$('.evt-footer-mov').click(function(){
			if($(window).width()<=767){
				$(this).toggleClass('active');
				$(this).next().slideToggle();
				$(this).parent().toggleClass('paddingbottom');	
			}
		});
	   
	});
</script>