<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
<div class="container">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
				<div class="row">
					<div class="col-md-5 col-sm-12 col-xs-12">
						<div class="text-newletter">
							<h3><span><?php echo __('Sign up')?></span><?php echo __(' FOR SPECIAL PROMOTIONS')?></h3>
							<p><?php echo __('Get exclusive deals you wont find anywhere else straight to your inbox!')?></p>
						</div>
						<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ //echo __('Sign Up for Our Newsletter:') ?></span></label>
					</div>
					<div class="col-md-7 col-sm-12 col-xs-12">
						<div class="control">
							<input name="email" type="email" id="newsletter"
										placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
										data-validate="{required:true, 'validate-email':true}"/>
							<div class="actions">
								<button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
									<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
								</button>
							</div>
						</div>
					</div>
				</div>
            </div>
            
        </form>
    </div>
</div>
</div>
