<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Información de Identificación') ?></span></legend><br>

    <div class="field rut required">
        <label for="rut" class="label"><span><?php /* @escapeNotVerified */ echo __('Rut') ?></span></label>
        <div class="control">
            <input type="text" name="rut" id="rut" title="<?php /* @escapeNotVerified */ echo __('Rut') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>
