<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog post list toolbar template
 *
 * @var $block \Plazathemes\Blog\Block\Post\PostList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-blog-posts" data-mage-init='<?php echo $block->getWidgetOptionsJson(); ?>'>
        <?php echo $block->getPagerHtml() ?>
    </div>
<?php endif ?>
